[package]
name = "aero-qemu-bridge"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
native-renderer = ["aero-devices-gpu/aerogpu-native"]

[dependencies]
aero-devices = { path = "../devices" }
aero-devices-gpu = { path = "../aero-devices-gpu" }
memory = { path = "../memory" }
